# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dafcfede9a06a6e009b52d7d704a102f"
name = "product-feedback"
handle = "product-feedback-2"
application_url = "https://6b8d586c5906.ngrok-free.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_app_proxy"

[app_proxy]
url = "https://6b8d586c5906.ngrok-free.app/proxy"
subpath = "proxy"
prefix = "apps"

[auth]
redirect_urls = ["https://6b8d586c5906.ngrok-free.app/auth/callback", "https://decor-other-glucose-walls.trycloudflare.com/auth/shopify/callback", "https://decor-other-glucose-walls.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
